In [1]:
#! pip install opencv-python

In [2]:
import cv2  # import opencv-python lib. 

In [3]:
cv2.imread

<function imread>

In [4]:
pwd # present working directory

'C:\\Users\\nitin\\Computer Vision'

In [5]:
image=cv2.imread("cat.jpg")  # imread func reads the cat image using pixel values

In [6]:
image    # 3-D array

array([[[168, 174, 187],
        [167, 173, 186],
        [165, 171, 184],
        ...,
        [202, 206, 207],
        [202, 206, 207],
        [202, 206, 207]],

       [[167, 173, 186],
        [167, 173, 186],
        [165, 171, 184],
        ...,
        [202, 206, 207],
        [202, 206, 207],
        [202, 206, 207]],

       [[167, 173, 186],
        [167, 173, 186],
        [166, 172, 185],
        ...,
        [202, 206, 207],
        [202, 206, 207],
        [202, 206, 207]],

       ...,

       [[217, 223, 212],
        [217, 223, 212],
        [217, 223, 212],
        ...,
        [214, 215, 206],
        [211, 214, 205],
        [211, 214, 205]],

       [[217, 223, 212],
        [217, 223, 212],
        [217, 223, 212],
        ...,
        [211, 212, 203],
        [209, 212, 203],
        [209, 212, 203]],

       [[217, 223, 212],
        [217, 223, 212],
        [217, 223, 212],
        ...,
        [209, 210, 201],
        [210, 211, 202],
        [210, 211, 202]]

In [7]:
type(image)

numpy.ndarray

In [8]:
image.shape  # Height, Width, no. of layers in the image (3 layers: bgr i.e. blue, green, red)

(901, 1200, 3)

In [9]:
901*1200*3  # total no. of pixels in cat image

3243600

In [10]:
print("height:{}".format(image.shape[0]))
print("width:{}".format(image.shape[1]))
print("channels:{}".format(image.shape[2]))

height:901
width:1200
channels:3


In [11]:
image[0] # displays pixel values wrt height of the image

array([[168, 174, 187],
       [167, 173, 186],
       [165, 171, 184],
       ...,
       [202, 206, 207],
       [202, 206, 207],
       [202, 206, 207]], dtype=uint8)

In [12]:
# visualize the image
# cat image is saved in var. image
cv2.imshow("myimage",image)  # load cat image into cv2 window
cv2.waitKey()              # we can pass for how many seconds we can keep the image on screen 
cv2.destroyAllWindows()    # it will close the cv2 window automatically

In [13]:
cv2.imshow("myimage",image)
cv2.waitKey(10000)         # keep the image for 10 sec. on the screen
cv2.destroyAllWindows()

In [14]:
cv2.imwrite("new_cat.jpg",image) # after reading the image, we can write the image to a new file

True

In [15]:
image=cv2.imread("cat.jpg")

In [16]:
cv2.imshow("myimage1",image)   # load cat image into cv2 window
cv2.waitKey()
cv2.destroyAllWindows()

In [17]:
image[0,0]   # pixel values of cat image at location (0,0) i.e. extreme top left position

array([168, 174, 187], dtype=uint8)

In [18]:
(b,g,r)=image[0,0] # opencv lib. reads the image in the format of b,g,r 

In [19]:
b

168

In [20]:
g

174

In [21]:
r

187

In [22]:
#the format in which we can see the image is rgb. So,change the format from bgr to rgb
print("Pixel at (0,0) - Red:{} Green:{} Blue:{}".format(r,g,b)) 

Pixel at (0,0) - Red:187 Green:174 Blue:168


In [23]:
image[400,400]  # pixel values of image at location (400,400)

array([134, 170, 224], dtype=uint8)

In [24]:
# slicing (0th to 25th row, 0th to 25th column)
image[0:25,0:25]=(0,255,255) # pixel value of green & red colors = 255 each, combination of green & red is yellow 
(b,g,r)=image[0,0]  # yellow color is at the top left corner
print("Pixel at (0,0) - Red:{}, Green:{}, Blue:{}".format(r,g,b))

Pixel at (0,0) - Red:255, Green:255, Blue:0


In [25]:
cv2.imshow("output",image)  # load cat image into cv2 window
cv2.waitKey(10000)          # 10 sec
cv2.destroyAllWindows()

In [26]:
# slicing (0th to 25th row, 0th to 25th column)
image[0:25,0:25]=(255,255,255) # pixel value of blue,green & red colors = 255 each, combination of blue, green & red is white 
(b,g,r)=image[0,0]  # white color is at the top left corner
print("Pixel at (0,0) - Red:{}, Green:{}, Blue:{}".format(r,g,b))

Pixel at (0,0) - Red:255, Green:255, Blue:255


In [27]:
cv2.imshow("output",image)  # load cat image into cv2 window
cv2.waitKey(10000)          # 10 sec
cv2.destroyAllWindows()

In [28]:
# slicing (0th to 25th row, 0th to 25th column)
image[0:25,0:25]=(0,0,0) # pixel value of blue,green & red colors = 0 each, so, black color is the final result
(b,g,r)=image[0,0]  # black color is at the top left corner
print("Pixel at (0,0) - Red:{}, Green:{}, Blue:{}".format(r,g,b))

Pixel at (0,0) - Red:0, Green:0, Blue:0


In [29]:
cv2.imshow("output",image)  # load cat image into cv2 window
cv2.waitKey(10000)          # 10 sec
cv2.destroyAllWindows()

In [30]:
# slicing (0th to 25th row, 0th to 25th column)
image[0:25,0:25]=(255,0,0) # pixel value of blue color= 255, so, blue color is the final result
(b,g,r)=image[0,0]  # blue color is at the top left corner
print("Pixel at (0,0) - Red:{}, Green:{}, Blue:{}".format(r,g,b))

Pixel at (0,0) - Red:0, Green:0, Blue:255


In [31]:
cv2.imshow("output",image)  # load cat image into cv2 window
cv2.waitKey(10000)          # 10 sec
cv2.destroyAllWindows()